project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://meffmadd.github.io/samplesurium/
  title: "Samplesurium"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/meffmadd/samplesurium
format:
  html:
    theme:
      - lumen
      - styles.scss
      - brand

